#define DISPLAY_RCLK_PIN  0
#define DISPLAY_SRCLK_PIN 1
#define DISPLAY_SER_PIN   2
#define DISPLAY_OE_PIN    11

#define CONSOLE_LEFT_BUTTON_PIN   3
#define CONSOLE_RIGHT_BUTTON_PIN  4

#define CONTROLLER_SHLD_PIN 5
#define CONTROLLER_CLK_PIN  6

#define CONTROLLER_1_SER_PIN    7
#define CONTROLLER_1_CONN_PIN   8
#define CONTROLLER_2_SER_PIN    9
#define CONTROLLER_2_CONN_PIN   10

#define MAX_DISPLAY_PIXELS  200
#define DISPLAY_INITIAL_BRIGHTNESS 8
